version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins-docker
    ports:
      - "8080:8080"
      - "50000:50000"
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:

